package com.example.demo.DTO;

import lombok.Data;

@Data
public class ForgotPasswordRequestDto {
    private String email;
    private String name;
    private String tel;

    // Getters and Setters are automatically generated by Lombok's @Data annotation
}
